[17-04-2025 16:57:54.00] Starting mark_absentees 
Traceback (most recent call last):
  File "C:\Users\Sins\OneDrive\Desktop\face_auth_backend - Copy\faceauth_attendance\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\Sins\OneDrive\Desktop\face_auth_backend - Copy\faceauth_attendance\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
    ~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_crontab'
[17-04-2025 16:57:55.11] Finished mark_absentees with exit code 1 
[17-04-2025 16:58:02.50] Starting mark_absentees 
Traceback (most recent call last):
  File "C:\Users\Sins\OneDrive\Desktop\face_auth_backend - Copy\faceauth_attendance\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\Sins\OneDrive\Desktop\face_auth_backend - Copy\faceauth_attendance\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
    ~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Sins\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_crontab'
[17-04-2025 16:58:03.27] Finished mark_absentees with exit code 1 
